### PR TITLE
(PPM) Use custom TIFF reader for loading cell map

### LINKED ISSUE #42: [Bug] PPM error when loading cell map > 1GB
### What happened?

big-cellmap

### Steps to reproduce

_No response_

### Version

_No response_

### How did you install the software?

None

### On which operating systems have you experienced this issue?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by csparker247**
This overhauls `TIFFIO.hpp` to fix some bugs and add new features:
- Added `tiffio::ReadTIFF` which can read single image, 8, 16, and 32bpc TIFF files with various pixel types.
- Added TIFFIO unit tests
- `tiffio::WriteTIFF` automatically write TIFFs > 4GB as BigTIFF.
- `tiffio::WriteTIFF` better handles obscure, unsupported color conversions (e.g. `CV_8SC3` and `CV_8SC4` are not supported by `cv::cvtColor`)
- (PerPixelMap) Use `tiffio::ReadTIFF` for loading the cell map (fixes #42)
- (PerPixelMap) Better error handling for mask and cell map loading
- (PPM Tests) Test mask and cell map serialization

### CODE REVIEW

File: core/src/TIFFIO.cpp [hunk 1]
```diff
@@ -16,6 +16,101 @@ namespace lt
...
+        }
+    } else if (config == PLANARCONFIG_SEPARATE) {
+        std::runtime_error(
+            "Unsupported TIFF planar configuration: PLANARCONFIG_SEPARATE");
+    }
+
+    // Do channel conversion
+    cv::Mat imgCopy;
+    if (img.channels() == 3) {
+        cv::cvtColor(img, imgCopy, cv::COLOR_BGR2RGB);
```
Comment (csparker247) [inline core/src/TIFFIO.cpp]:
```suggestion
        cv::cvtColor(img, imgCopy, cv::COLOR_RGB2BGR);
```

File: core/src/TIFFIO.cpp [hunk 2]
```diff
@@ -16,6 +16,101 @@ namespace lt
...
+    } else if (img.channels() == 4) {
+        cv::cvtColor(img, imgCopy, cv::COLOR_BGRA2RGBA);
```
Comment (csparker247) [inline core/src/TIFFIO.cpp]:
```suggestion
        cv::cvtColor(img, imgCopy, cv::COLOR_RGBA2BGRA);
```

**Comment by csparker247** [comment]
For posterity, here's the code I used to test BigTIFF support. It's not a unit test because I don't want to write 4GB files in the unit tests:
```c++
#include <limits>
#include <random>
#include <iostream>

#include "vc/core/io/TIFFIO.hpp"
#include "vc/core/io/ImageIO.hpp"

using namespace volcart;

auto main() -> int
{
    using ElemT = std::uint16_t;
    auto low = std::numeric_limits<ElemT>::min();
    auto high = std::numeric_limits<ElemT>::max();
    static std::uniform_int_distribution<ElemT> dist(low, high);
    static std::default_random_engine gen;

    std::cout << "Creating big random image...\n";
    cv::Mat bigImg(50000, 50000, CV_16UC1);
    std::generate(bigImg.begin<ElemT>(), bigImg.end<ElemT>(), []() { return dist(gen); });
    std::cout << "Writing image...\n";
    tiffio::WriteTIFF("big_image.tif", bigImg, tiffio::Compression::NONE);

    std::cout << "OpenCV: Reading image...\n";
    try {
        const cv::Mat img = volcart::ReadImage("big_image.tif");
        std::cout << img.rows << "x" << img.cols << "\n";
        std::cout << cv::typeToString(img.type()) << "\n";
    } catch (const std::exception& e) {
        std::cout << "OpenCV: Failed to read: " << e.what() << "\n";
    }

    std::cout << "TIFFIO: Reading image...\n";
    try {
        const cv::Mat img = tiffio::ReadTIFF("big_image.tif");
        std::cout << img.rows << "x" << img.cols << "\n";
        std::cout << cv::typeToString(img.type()) << "\n";
    } catch (const std::exception& e) {
        std::cout << "TIFFIO: Failed to read: " << e.what() << "\n";
    }
}
```
